name: Typo in individual record
description: Let us know about a small, obvious mistake in an individual record (page) on Usaybia.net
title: "Typo: "
labels: [typo, triage, https://usaybia.net/person/1]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to let us know!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: uri
    attributes:
      label: URI of the page with the mistake
      description: Please provide the URI of the page where you found the mistake.
      placeholder: ex. https://usaybia.net/person/1
    validations:
      required: true
  - type: textarea
    id: whatIs
    attributes:
      label: What does the page say?
      placeholder: Please copy the mistake here with a few words of context.
    validations:
      required: true