name: Typo in individual record
description: Let us know about a small, obvious mistake in an individual record (page) on Usaybia.net
title: "Typo: "
labels: [typo, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to let us know!
  - type: input
    id: uri
    attributes:
      label: URI of the page with the mistake
      description: Please provide the URI of the page where you found the mistake.
      placeholder: ex. https://usaybia.net/person/1
    validations:
      required: true
  - type: textarea
    id: what-is
    attributes:
      label: What does the page say?
      placeholder: Please copy the mistake here with a few words of context.
    validations:
      required: true
  - type: textarea
    id: what-should-be
    attributes:
      label: What SHOULD the page say?
      placeholder: Your corrected version of the text
    validations:
      required: true
  - type: dropdown
    id: acknowledgement
    attributes:
      label: Public Acknowledgement
      description: Is it okay if we publicly acknowledge your contribution using the name or username listed in your GitHub profile?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: Your other comments, if any